tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y openssh-server
      sudo apt-get install -y npm
      sudo npm install -g wstunnel
  - command: |
      sudo service ssh start
      wstunnel -s 0.0.0.0:80 &
ports:
  - port: 80
    onOpen: open-preview
